### PR TITLE
Update camp_solver.c

### PR DESCRIPTION
**Pull request by cguzman95**
https://github.com/open-atmos/camp/issues/7#issuecomment-1004985073

### CODE REVIEW

**Comment by cguzman95** [comment]
Seems it only fails test_MONARCH_2. This test is still relevant or it does not matter? @cguzman95

**Comment by mattldawson** [comment]
> Seems it only fails test_MONARCH_2. This test is still relevant or it does not matter? @mattldawson

Yeah, it's still relevant. You might try other values for the scaling, although it looks like you've tried this already. If this is just a problem for profiling, can you just disable it when you're doing the profiling?

**Comment by mattldawson** [comment]
You could also try:
```
h_j *= 0.95 + 0.1 * iter / (double)GUESS_MAX_ITER;
```

This worked for me. I think the important part is that the scaling is not the same at each iteration.

**Comment by cguzman95** [comment]
Fine now

**Pull request merged**
